// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.dsproject;

public interface displayGUIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:displayGUIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dgmessage = 1;</code>
   */
  java.lang.String getDgmessage();
  /**
   * <code>string dgmessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getDgmessageBytes();
}
