// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.dsproject;

public interface displayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:displayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string drResponse = 1;</code>
   */
  java.lang.String getDrResponse();
  /**
   * <code>string drResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getDrResponseBytes();

  /**
   * <code>int32 drResponseCode = 2;</code>
   */
  int getDrResponseCode();
}
