// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.dsproject;

public interface displayGUIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:displayGUIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dgresponse = 1;</code>
   */
  java.lang.String getDgresponse();
  /**
   * <code>string dgresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getDgresponseBytes();

  /**
   * <code>int32 dgresponsecode = 2;</code>
   */
  int getDgresponsecode();
}
