// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.dsproject;

public interface displayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:displayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string display = 1;</code>
   */
  java.lang.String getDisplay();
  /**
   * <code>string display = 1;</code>
   */
  com.google.protobuf.ByteString
      getDisplayBytes();
}
