// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.dsproject;

public interface tdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string terminate = 1;</code>
   */
  java.lang.String getTerminate();
  /**
   * <code>string terminate = 1;</code>
   */
  com.google.protobuf.ByteString
      getTerminateBytes();
}
