// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.dsproject;

public interface tdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string terResponse = 1;</code>
   */
  java.lang.String getTerResponse();
  /**
   * <code>string terResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getTerResponseBytes();

  /**
   * <code>int32 trResponseCode = 2;</code>
   */
  int getTrResponseCode();
}
