// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.dsproject;

public interface terminateGUIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:terminateGUIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tgresponse = 1;</code>
   */
  java.lang.String getTgresponse();
  /**
   * <code>string tgresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getTgresponseBytes();

  /**
   * <code>int32 tgresponsecode = 2;</code>
   */
  int getTgresponsecode();
}
