// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.dsproject;

public interface terminateGUIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:terminateGUIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tgmessage = 1;</code>
   */
  java.lang.String getTgmessage();
  /**
   * <code>string tgmessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getTgmessageBytes();
}
